name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch: 

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd evalscope-jsonl-viewer
          npm install

      - name: Build
        run: |
          cd evalscope-jsonl-viewer
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: evalscope-jsonl-viewer/dist
          publish_branch: gh-pages
